@echo off
echo Starting Mohamed Al-Fateh School Website...
echo.
echo Installing dependencies...
call npm install
echo.
echo Building the project...
call npm run build
echo.
echo Starting development server...
call npm run dev
pause
